[package]
name = "test-spleentt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.83"
argh = "0.1.12"
bdf = { git = "https://github.com/meh/rust-bdf" }
minifb = "0.25.0"
